### PR TITLE
Added support for the `=` CIGAR operator.

### PR DESCRIPTION
**Pull request by jonn-smith**

### CODE REVIEW

**Comment by jonn-smith** [comment]
@fairliereese I just started working with TALON but I have some data from an aligner that produces `=` CIGAR operators. 

Here's a patch to make TALON support the `=` operator.

**Comment by jonn-smith** [comment]
@fairliereese Any thoughts on this?  I've added tests and it works for my larger dataset.

**Comment by fairliereese** [comment]
Thanks a lot for reminding me of this! I appreciate the thorough work you've done :)

**Comment by jonn-smith** [comment]
No prob!  I figured you're like me and saw it, then never got back to it 😄

**Pull request merged**
